// AUTO-GENERATED by AdvanxJS compiler — do not edit.
// Article VIII — Self-Mapping: this manifest is the Agent's contract for the SPA route table.
export const routes = {
  "/about": { logicPath: "./about/logic.ts", viewPath: "./about/view.html", stylePath: "./about/style.css" },
  "/": { logicPath: "./index/logic.ts", viewPath: "./index/view.html", stylePath: "./index/style.css" },
};
