import fs from "fs";
import path from "path";
import { analyzeLogic } from "./analyze";
import { parseView } from "./parseView";
import { validateBindings } from "./validate";

export async function compilePages(rootDir: string): Promise<number> {
  const pagesDir = path.join(rootDir, "src", "pages");
  if (!fs.existsSync(pagesDir)) {
    throw new Error(`No src/pages directory found at ${pagesDir}`);
  }

  const entries = fs
    .readdirSync(pagesDir, { withFileTypes: true })
    .filter(e => e.isDirectory())
    .map(e => e.name)
    .sort();

  if (entries.length === 0) {
    throw new Error(`src/pages exists but contains no page subfolders.`);
  }

  type PageInfo = { name: string; route: string; view: string; style: string };
  const pages: PageInfo[] = [];

  for (const name of entries) {
    const pageDir = path.join(pagesDir, name);
    const viewPath = path.join(pageDir, "view.html");
    const logicPath = path.join(pageDir, "logic.ts");
    const stylePath = path.join(pageDir, "style.css");

    for (const [label, p] of [["view.html", viewPath], ["logic.ts", logicPath], ["style.css", stylePath]] as const) {
      if (!fs.existsSync(p)) {
        throw new Error(`Page "${name}" is missing ${label} (Article I — Trinity of Separation).`);
      }
    }

    const view = fs.readFileSync(viewPath, "utf-8");
    const logicCode = fs.readFileSync(logicPath, "utf-8");
    const style = fs.readFileSync(stylePath, "utf-8");

    const logic = analyzeLogic(logicCode);
    const bindings = parseView(view);
    validateBindings(bindings, logic);

    const route = name === "index" ? "/" : "/" + name;

    const metadata = {
      component: name,
      route,
      signals: logic.signals,
      computed: logic.computed,
      actions: logic.actions,
      structure: {
        mustaches: bindings.mustaches,
        conditionals: bindings.conditionals,
        events: bindings.events,
        loops: bindings.loops,
        models: bindings.models,
      },
      tokens_hint: "This page is AdvanxJS compliant. Logic and View are decoupled.",
    };
    fs.writeFileSync(path.join(pageDir, ".advanx-meta.json"), JSON.stringify(metadata, null, 2));

    pages.push({ name, route, view, style });
  }

  const manifestLines = [
    "// AUTO-GENERATED by AdvanxJS compiler — do not edit.",
    "// Article VIII — Self-Mapping: this manifest is the Agent's contract for the SPA route table.",
    "export const routes = {",
    ...pages.map(p =>
      `  ${JSON.stringify(p.route)}: { logicPath: ${JSON.stringify(`./${p.name}/logic.ts`)}, viewPath: ${JSON.stringify(`./${p.name}/view.html`)}, stylePath: ${JSON.stringify(`./${p.name}/style.css`)} },`
    ),
    "};",
    "",
  ];
  fs.writeFileSync(path.join(pagesDir, "routes.js"), manifestLines.join("\n"));

  const dist = path.join(rootDir, "dist");
  if (!fs.existsSync(dist)) fs.mkdirSync(dist, { recursive: true });

  const scaffoldedRuntime = path.join(rootDir, "src", "lib", "advanx", "runtime.ts");
  const runtimeImport = fs.existsSync(scaffoldedRuntime)
    ? "../src/lib/advanx/runtime.ts"
    : "../../../packages/core/src/runtime.ts";

  const imports = pages
    .map((p, i) => `import * as p${i} from "../src/pages/${p.name}/logic.ts";`)
    .join("\n");
  const routesEntries = pages
    .map((p, i) =>
      `  ${JSON.stringify(p.route)}: { view: ${JSON.stringify(p.view)}, style: ${JSON.stringify(p.style)}, logic: p${i} },`
    )
    .join("\n");

  const entry =
    `${imports}
import { initRouter } from "${runtimeImport}";
const routes = {
${routesEntries}
};
initRouter(routes);
`;
  fs.writeFileSync(path.join(dist, "entry.ts"), entry);

  const runtimeAbs = path.resolve(dist, runtimeImport);
  const signalsPath = Bun.resolveSync("@preact/signals-core", path.dirname(runtimeAbs));

  const result = await Bun.build({
    entrypoints: [path.join(dist, "entry.ts")],
    outdir: dist,
    naming: "bundle.js",
    format: "iife",
    throw: false,
    plugins: [{
      name: "dedupe-signals",
      setup(build) {
        build.onResolve({ filter: /^@preact\/signals-core$/ }, () => ({ path: signalsPath }));
      },
    }],
  });
  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error("Build failed — see logs above for details.");
  }

  const html = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8" /><title>AdvanxJS App</title></head>
<body><div id="router-view"></div><script src="./bundle.js"></script></body>
</html>
`;
  fs.writeFileSync(path.join(dist, "index.html"), html);

  return pages.length;
}
